name: Tests

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Debug structure
        run: ls -R

      - name: Find pom.xml (debug)
        run: find . -name pom.xml

      - name: Run tests
        run: mvn test
